# Generated by Django 2.0.6 on 2018-06-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMy', '0002_auto_20180611_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default='str', verbose_name='Описание отделов'),
            preserve_default=False,
        ),
    ]
