# Generated by Django 2.0.6 on 2018-06-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMy', '0003_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items', verbose_name='Изображение'),
        ),
    ]
